### ISSUE TITLE
Document `/api/health` endpoint

### ISSUE THREAD

**Issue by kirushik** [paritytech/wiki#119]
As mentione in [this comment](https://github.com/paritytech/parity/issues/7560#issuecomment-388614837), there's nothing about health endpoint in our wiki.

Considering those endpoints are extrmely useful for almost everyone running parity in headless/daemon mode — can we please add it to the documentation?

Like, which errors codes mean what, and what additional info does it provide... should be pretty straightforward, but requires some amount of data-digging, as usual.

**Comment by Tbaut** [comment]
Thanks Kirill, I'm not familiar with it, could you please point me in the right direction?

**Comment by Tbaut** [comment]
calling http://127.0.0.1:8545/api/health with a running node.

```
{
    "Ok": {
        "peers": {
            "status": "ok",
            "message": "",
            "details": [14, 25]
        },
        "sync": {
            "status": "ok",
            "message": "",
            "details": false
        },
        "time": {
            "status": "ok",
            "message": "",
            "details": 284
        }
    }
}
```

**Comment by Tbaut** [comment]
Closing as the health api has been removed.

**Comment by Levino** [comment]
What? So how to run parity behind a reverse proxy then?
