### ISSUE TITLE
Update Parity Signer wiki page with guidelines

### ISSUE THREAD

**Issue by a13xndra** [paritytech/wiki#127]
We need to add the following text to the Parity Signer wiki page https://wiki.parity.io/Parity-Signer-Mobile-App-MyCrypto-tutorial :

**Since we cannot guarantee the safety of your phone, we recommend you follow these guidelines when installing and using Parity Signer:**

- Wipe the phone before installing Parity Signer.
- Once Parity Signer is installed, always keep the phone completely disconnected from WIFI and cellular network connections. 
- Only charge the phone on a power outlet that is never connected to the internet. Only charge the phone with the manufacturer's charging adapter. Do not charge the phone on public USB chargers.

**Comment by Tbaut** [comment]
Hey Alex, we have this (phrased differently) here: https://wiki.parity.io/Parity-Signer-Mobile-App
Do you want to add it to the mycrypto anyway?
