### ISSUE TITLE
Add `private` API to `JSONRPC Guide`

### ISSUE THREAD

**Issue by maciejhirsz** [paritytech/wiki#155]
The RPC methods for Private Transactions are currently documented at https://wiki.parity.io/Private-Transactions.html

They should be uniform with the other APIs we have, use the same formatting and examples. Some parts of the document currently might be unintelligible to end users (eg: notion of `struct`s and especially `Vec`s are intrinsic to Rust and might leave frontend engineers only familiar with JSON-RPC confused).

**Comment by Tbaut** [comment]
Relates to https://github.com/paritytech/wiki/issues/58 IMO
