### ISSUE TITLE
Spec json is invalid: missing field `gasLimitBoundDivisor` 

### ISSUE THREAD

**Issue by 5chdn** [paritytech/wiki#159]
> Can you guys update the demoPOA to reflect these changes?
https://wiki.parity.io/Demo-PoA-tutorial.html

From https://github.com/paritytech/parity/issues/6916

**Comment by Tbaut** [comment]
Already there IMHO:
![image](https://user-images.githubusercontent.com/33178835/41649423-d160b188-747b-11e8-94e4-002aae330b04.png)

**Comment by themandalore** [comment]
It's on the third portion where you complete the specs

**Comment by 5chdn** [comment]
Well spotted :+1:
