### ISSUE TITLE
Inconsistencies between docs and get-parity.sh #36

### ISSUE THREAD

**Issue by 5chdn** [paritytech/wiki#179]
> In the setup documentation it states  `you won’t get the cutting edge features` from the bash script however it appears to be installing the latest beta version while I would expect it to be installing a stable release. 

> It also goes on to say `this script will also offer to install the Netstats client and connect it to ethstats.net` but this appears to be implemented in the `install-deps.sh` script which is not referenced in the `get-parity.sh` script and no such prompt is given. Working on confirming the `install-deps.sh` in addition to the `get-parity.sh` would successfully setup netstats.

https://github.com/paritytech/scripts/issues/36

https://wiki.parity.io/Setup

**Comment by ansermino** [comment]
I am still not prompted for netstats installation. Is that a documentation or script issue?

**Comment by 5chdn** [comment]
That's a docs issue.
