### ISSUE TITLE
Small typo on eth_getTransactionReceipt

### ISSUE THREAD

**Issue by bdsomer** [paritytech/wiki#187]
https://wiki.parity.io/JSONRPC-eth-module.html#eth_gettransactionreceipt

Shows a request with transaction hash `"0xb903239f8543d04b5dc1ba6579132b143087c68db1b2168786408fcbce568238"` but the response has a `transactionHash` key with value `"0x444172bef57ad978655171a8af2cfd89baa02a97fcb773067aef7794d6913374"`.

This is a small issue that could probably be fixed quickly.

**Comment by Tbaut** [comment]
Same as your other question, it would be great if the community could help to make these small changes: https://wiki.parity.io/FAQ#how-to-contribute-to-this-wiki-documentation

**Comment by bdsomer** [comment]
Never mind, I was looking at the `params` example. In fact, the hash in the sample request and sample response are the same.

This issue is not valid.
