### ISSUE TITLE
trace_rawTransaction response is missing fields

### ISSUE THREAD

**Issue by bdsomer** [paritytech/wiki#188]
https://wiki.parity.io/JSONRPC-trace-module#trace_rawtransaction

The response is missing `id` and `jsonrpc` fields in the parent object. It is also missing a `result` key preceding the only child of the parent object. Should be a small fix 👍

**Comment by Tbaut** [comment]
Hey, I just created a small how to submit pull request and make this happen: https://wiki.parity.io/FAQ#how-to-contribute-to-this-wiki-documentation

Would you mind having a look at it and tell me if it's easy enough to understand?
