### ISSUE TITLE
Doubt about 'action'

### ISSUE THREAD

**Issue by seafooler** [paritytech/wiki#219]
I used to think that `action` consists of both `transactions` and `internal transactions`. The latter includes the invocation of smart contracts. 
However, when I trace the transaction `0x77656b0b74ea1f8b158067c8371617aae7ab06f05c6c13001606a763688602c3` with method `trace_transaction`, there is only one action without listing the invocation of contract `0xaf30d2a7e90d7dc361c8c4585e9bb7d2f6f15bc7 `. 

Did I mistake understanding the meaning of `action`? I cannot find enough materials to explain it. Could anyone help me to figure it out? Thanks in advance.

**Comment by Tbaut** [comment]
Thanks for your question, I believe it refers to Parity Ethereum rather than a particular page of this wiki. Please ask your question in the [Parity Ethereum repo]([parity-ethereum](https://github.com/paritytech/parity-ethereum)).
