### ISSUE TITLE
the demo-spec.json  in Demo PoA-Tutorial

### ISSUE THREAD

**Issue by Amaleid** [paritytech/wiki#229]
Hi im new in this filed and i try to setting up two Parity nodes locally and sending transactions between them!
so im following [Demo PoA-Tutorial](https://github.com/paritytech/wiki/blob/master/Demo-PoA-tutorial.md) 
im using Ubuntu server 
my question is where i can put this file ?(demo-spec.json) i mean the location 

` parity  --chain demo-spec.json -d /tmp/parity0 --port 30300 --jsonrpc-port 8540 --ws-port 8450 --jsonrpc-apis web3,eth,net,personal,parity,parity_set,traces,rpc,parity_accounts
Could not load specification file at demo-spec.json: No such file or directory (os error 2)
`
and can someone just explain for me the steps plz as the tutorial is not clear for me
thank you

**Comment by Tbaut** [comment]
Discussion on Gittter + wrong repo.
