### ISSUE TITLE
Update Mining wiki

### ISSUE THREAD

**Issue by uluhonolulu** [paritytech/wiki#234]
Parity mining wiki suggests running `ethminer -G`, but the current version (0.16) responds with an error: "At least one pool URL must be specified". https://github.com/ethereum-mining/ethminer/issues/1552#issuecomment-419461416 suggests we use `ethminer -G -P http://127.0.0.1:8545`. If we use Stratum with default setup, I found that `ethminer -G -P stratum+tcp://127.0.0.1:8008` works, provided that you have OpenCL drivers of version at least 1.2.

**Comment by Tbaut** [comment]
Thanks for the heads up, PR are [always welcome](https://wiki.parity.io/FAQ#how-to-contribute-to-this-wiki-documentation) :)

**Comment by uluhonolulu** [comment]
@Tbaut done.

**Comment by Tbaut** [comment]
:+1: thanks a lot
