### ISSUE TITLE
Readme product links are broken

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/wiki#253]
The links to these products in the Readme are broken:

- Parity Ethereum
- Parity Substrate
- Parity Fether
- Parity Signer
- Parity UI

**Comment by Tbaut** [comment]
What do you mean? They redirect to the wiki for me. Tested on mobile also (android)

**Comment by ltfschoen** [comment]
Here's an animated gif of what's happening at my end using latest Google Chrome Version 69.0.3497.100 ![untitled](https://user-images.githubusercontent.com/6226175/46068407-6eb26e80-c1bc-11e8-8976-54f18e4e66e1.gif)

I've also tried with 

For example, when I click the link "Parity Ethereum" link it takes me to https://github.com/paritytech/wiki/blob/master/Parity-Ethereum, which I gathered was because the Markdown code is `[Parity Ethereum](Parity-Ethereum)` (i.e. [name-to-display](url-to-open-on-click)), since that's how I use Markdown. So I just replaced it with the actual url of the product.

**Comment by ltfschoen** [comment]
I just tried on my Android using latest Samsung Internet v 7.4.00.70 and they all return 404 too

**Comment by Tbaut** [comment]
Oh. The wiki page is http://wiki.parity.io/
This is just the repo containing the wiki. We should consider creating a home page and redirect per default to it. And edit the readme.

**Comment by ltfschoen** [comment]
Oh, I see what you mean. The URL's should be pointing to the local Markdown files, but were missing the .md extension. I've created a PR https://github.com/paritytech/wiki/pull/255

**Comment by Tbaut** [comment]
I'd like to redirect users to the wiki as much as possible rather than leave them reading the md files in the repo. That's addressed in https://github.com/paritytech/wiki/pull/256
