### ISSUE TITLE
Add maximumUncleCount to wiki

### ISSUE THREAD

**Issue by jbentke** [paritytech/wiki#29]
Parity 1.9 introduced the parameter option `maximunUncleCount` which is missing on https://wiki.parity.io/Chain-specification.

A little bit of information would be good as well as the default option 0 potentially breaks older aura chains.

**Comment by 5chdn** [comment]
Yes. Plus from 1.10:

- empty step transition, max empty steps
- wasm activation

**Comment by 5chdn** [comment]
/// Block at which maximum uncle count should be considered.
	#[serde(rename="maximumUncleCountTransition")]
	pub maximum_uncle_count_transition: Option<Uint>,
	/// Maximum number of accepted uncles.
	#[serde(rename="maximumUncleCount")]
	pub maximum_uncle_count: Option<Uint>,
	/// Block at which empty step messages should start.
	#[serde(rename="emptyStepsTransition")]
	pub empty_steps_transition: Option<Uint>,
	/// Maximum number of accepted empty steps.
	#[serde(rename="maximumEmptySteps")]
	pub maximum_empty_steps: Option<Uint>,

**Comment by 5chdn** [comment]
default max uncle count:
- pow ethash 2 (hardcoded)
- poa aura 0

default max uncle count transition
- pow ethash n/a
- poa aura 0
