### ISSUE TITLE
The link is broken

### ISSUE THREAD

**Issue by TriplEight** [paritytech/wiki#299]
The only link from https://github.com/paritytech/wiki/blob/master/Configuring-Parity.md is broken.
This page is pretty important because it's mentioned from [one](https://ethereum.stackexchange.com/questions/125/how-do-i-set-up-a-private-ethereum-network) of the frequent FAQ pages, [this](https://ethereum.stackexchange.com/a/42716/48949) commit.

**Comment by joshua-mir** [comment]
Fixed, thanks!
