### ISSUE TITLE
Is the Extrinsic format document for substrate still up to date with sr25519 changes?

### ISSUE THREAD

**Issue by xlc** [paritytech/wiki#313]
This document still refers to Ed25519 and no reference to sr25519 at all.

https://github.com/paritytech/wiki/blob/master/Extrinsic.md#the-extrinsic-format-for-node

**Comment by joshua-mir** [comment]
We should probably link out for all substrate docs - https://docs.substrate.dev/docs/extrinsic for example is the up-to-date extrinsic documentation.

**Comment by joshua-mir** [comment]
And that's exactly what we've done
