### ISSUE TITLE
Document the hardcoded sync feature

### ISSUE THREAD

**Issue by tomaka** [paritytech/wiki#57]
I'm not confident in my writing skills, so I'd be grateful if someone is willing to tackle this.

The hardcoded sync feature makes the light client automatically sync to a specific block when there is no existing database (if you have a DB, this DB will be used, even if it is behind the hardcoded block).

Consequently the chainspec can contain the infos required for the hardcoded sync. These info can be generated by running `parity export-hardcoded-sync`, which is useful if you want to do this for a custom chain.

**Comment by Tbaut** [comment]
Happy to take it ;)
