### ISSUE TITLE
Document the tracing ability

### ISSUE THREAD

**Issue by Tbaut** [paritytech/wiki#60]
parity --log-file /path/to/parity.log

And set the log level to error, warn, info, debug or trace, with:

`parity -lsync,tpc=trace`

Where the following modules can be traced: account_bloom, basicauthority, chain, client, dapps, discovery, diskmap, enact, engine, estimate_gas, ethash, executive, ext, external_tx, externalities, fatdb, fetch, hypervisor, ipc, jdb, journaldb, les, les_provider, local_store, migration, miner, mode, network, on_demand, own_tx, perf, poa, rcdb, shutdown, signer, snapshot, snapshot_io, snapshot_watcher, spec, state, stats, stratum, sync, trie, txqueue, and / or updater.

**Comment by 5chdn** [comment]
I have written this two years ago. https://ethereum.stackexchange.com/questions/3331/how-to-make-parity-write-logs

Might need some updates. :)
