### ISSUE TITLE
Enhance chain spec

### ISSUE THREAD

**Issue by Tbaut** [paritytech/wiki#64]
Add some more info : 

- Name is returned by RPC (not sure about that though) and used as a folder name for database files. If it contains spaces, you should add some dataDir parameter without spaces
- Blocks in AuRa still have difficulty, the score is calculated according to how many blocks where "in-step" - this defines the fork choice rule as well. Genesis block is regular block - it needs everything (e.g. to be returned via RPC or to be used as a base for calculations of the difficulty of the next block)
- Constructor in accounts is a bytecode to deploy a pre-defined contract. The constructor bytecode is run when the genesis is created and the code returned by the "constructor" is actually stored in the genesis state

**Comment by bjornwgnr** [comment]
Also, the `"params"`-section seems to be outdated. See https://wiki.parity.io/Permissioning
