### ISSUE TITLE
Document security best practices

### ISSUE THREAD

**Issue by Tbaut** [paritytech/wiki#82]
- Prefer [personal_sendTransaction](https://wiki.parity.io/JSONRPC-personal-module#personal_sendtransaction) over unlockAccount to securely send transactions without leaving an account unlocked.
- Do not use `all`/`0.0.0.0` for `--ws-interface`, `--ws-hosts`, `--ws-origins` and prefer a proper IP address/domain.
- Do not use `all`/`0.0.0.0` for `--jsonrpc-interface`, `--jsonrpc-hosts`, `--jsonrpc-origins` and prefer a proper IP address/domain.
- Do not use `--unsafe-expose` on a production server
- To access a server SSH tunneling is the way to go

Added by Tomek:
- Regular users should not use `--unlock`.
- Limit the `--jsonrpc-apis` if you don't need everything
- Disable unused servers: `--no-ws` `--no-ipc`

**Comment by Tbaut** [comment]
@kirushik @folsen @tomusdrw @5chdn could you please correct/complement the list above?

**Comment by tomusdrw** [comment]
I think we should suggest not using `all/0.0.0.0` for parameters and instead use very specific values, would be awesome to prepare couple of common problems scenarios. like `--jsonrpc-interface <IP>` and `--jsonrpc-hosts <mydomain>`

Some other suggestions:
1. Regular users should not use `--unlock`.
2. Limit the `--jsonrpc-apis` if you don't need everything
3. Disable unused servers: `--no-ws` `--no-ipc`

**Comment by Tbaut** [comment]
Thanks for your input @kirushik, I removed it.

**Comment by Tbaut** [comment]
cc @ddorgan if you want to have a look and add anything, I'll add it soon to the wiki.
